### ISSUE TITLE
code highlight

### ISSUE THREAD

**Issue by yiqiok** [halogenica/beautifulhugo#10]
the code highlight function doesn't work . even in DEMO

**Comment by halogenica** [comment]
Thank you for pointing out the broken highlighting on the demo!

I just verified that highlighting does work however it requires pygments to be installed (install python, then run "pip install Pygments"). This is is supposedly one of the standard methods of server side highlighting supported by hugo, which can be seen on the following page: https://gohugo.io/extras/highlighting/

It certainly seems that the hugo server used to generate the demos does not have this installed. Moreover, it is easy to miss the instructions I have given to install it (which can be found in the readme under the "Syntax Highlighting" section). For those reasons, and since the theme this was ported from does not use pygment highlighting, I will consider replacing the server side highlighting with client side highlighting. 

Hopefully the problem you're seeing is fixed with the simple pygments install, and I will close this bug. If not, then I hope a future update to perform client side highlighting will fix your problem.

**Comment by halogenica** [comment]
I just added client side syntax highlighting support with 938766f54f6e8cf3ec7c175606ac7511a4cfd1c9. I hope that helps!

**Comment by yiqiok** [comment]
Hi halogenica ! Thanks a lot . I just using "~~~" as a container of the code ,and it works .
