### ISSUE TITLE
"View All" categories & tags URL link broken

### ISSUE THREAD

**Issue by joakimvivas** [halogenica/beautifulhugo#142]
Hi! The pages "Categories" & "Tags" when I pushed into the "View All" option the URL it's broken because the absolute URL it's not correct, example: "mydomain.comtags/tagname".

**Comment by joakimvivas** [comment]
I changed the 22 line into the "terms.html" file on the theme directory with this command and the URL link now it's correct:

<a href="{{ $.Site.LanguagePrefix | absURL }}**/**{{ $data.Plural }}/{{ $value.Name | urlize }}/" class="list-group-item view-all">

**Comment by ulm0** [comment]
This happened to me as well, i'm running a i18n blog, and `View all` rendered `http://domain.com/estags/topicsinspanish` and `http://domain.com/entags/topicsinenglish`, after patching the `terms.html` file it renders properly `http://domain.com/es/tags/topicsinspanish` and `http://domain.com/en/tags/topicsinenglish`

**Comment by kaushalmodi** [comment]
@joakimvivas That suggestion could end up in the link have double slashes if `.Site.LanguagePrefix` already contains a string with a trailing `/`. e.g. if I have `baseURL` set to `https://example.com/`, AND I use only the default single "en" language, that will return `https://example.com/`.

Instead of manually always adding that `/`, we can do 

```
.Site.LanguagePrefix | absURL | replaceRE "[^/]$" "${0}/"
```

that basically adds the `/` as suffix **if it doesn't already exist**.

### Tests

```
{{ printf "%s<br />" ("foo" | absURL | replaceRE "[^/]$" "${0}/") | safeHTML }}  {{/* returns http://localhost:1313/foo/ */}}

{{ printf "%s<br />" ("foo/" | absURL | replaceRE "[^/]$" "${0}/") | safeHTML }} {{/* also returns http://localhost:1313/foo/ */}}
```

**Comment by halogenica** [comment]
Thanks! This should have been fixed; if it still occurs please let me know.
