### ISSUE TITLE
updated version and content doesn't show up right

### ISSUE THREAD

**Issue by jlozadad** [halogenica/beautifulhugo#223]
hello,

updated to latest version and content doesn't show up like missing images and such. http://jlozadad.io/ and you can see the project in https://gitlab.com/jlozada2426/blog

**Comment by VincentTam** [comment]
When I clicked the first link, your blog doesn't load in a few seconds.  I tried https://jlozada2426.gitlab.io/blog/ instead.

I *don't* understand your reason for making the code *viewable only to GitLab users*.  Anyone without a GitLab account who wishes to help you would have to apply one in order to debug your code.  You've caused inconvenience for GitHub users without a GitLab account, without preventing other GitLab users from redistributing your code due to its Apache 2.0 License.
