### ISSUE TITLE
Social icons not showing on Firefox

### ISSUE THREAD

**Issue by jackmitch** [halogenica/beautifulhugo#23]
Firefox 51.0.1 (64-bit) Linux

It seems that every other social icon is hidden on Firefox, however works OK in Chromium. See attached.

![icon-bug](https://cloud.githubusercontent.com/assets/5340320/23615499/8b2f44a6-027e-11e7-877a-ce0358515d64.png)

**Comment by halogenica** [comment]
This is bizarre. I just used firefox 51.0.1 (32 bit) on windows and Hugo v0.19 and everything works and displays correctly. If you inspect the view with firebug, etc. or view the page source, are the elements present and just not rendering?

I certainly don't think I'm infallible so I'd like to assume there's something I can fix here; but since my theoretically equivalent configuration doesn't reproduce the problem I can't fix it. It seems possible there may be some other bug? does clearing all of your online caches help?

**Comment by jackmitch** [comment]
Just testing this on my home machine with the exact same setup and it works. Must be a some sort of cache or machine specific issue, I'll investigate more tomorrow but lets close this as it seems moot.

Cheers!
