### ISSUE TITLE
Disqus Integration Question

### ISSUE THREAD

**Issue by refactorsaurusrex** [halogenica/beautifulhugo#4]
Hey, I was wondering if you could shed some light on something that's confusing me about the disqus integration in this theme. Why is it that there are calls to `{{ template "_internal/disqus.html" . }}` in both [single.html](https://github.com/halogenica/beautifulhugo/blob/c9e43406760c24a41d0be6d6938013ceccc75f3c/layouts/_default/single.html#L23) and [page.html](https://github.com/halogenica/beautifulhugo/blob/c9e43406760c24a41d0be6d6938013ceccc75f3c/layouts/partials/page.html#L22)? I can see it's also called in `post.html`, but what I'm trying to do is adjust the templates so that comments only appear on posts, not pages. The documentation on gohugo.io *seems* to indicate that only one call to `{{ template "_internal/disqus.html" . }}` is necessary, so I was confused why it's used in multiple places in this theme. 

Thanks in advance!

**Comment by halogenica** [comment]
Hey there, you're right! It doesn't need to be in single.html if it's already in page and post. I could have it either in single.html for all "single" entries (they can be called anything, page, post, project, etc. but I just set up the template to understand a a thing called a "page" and a thing called a "post"), or if you want it for a specific type of entry you can include that partial template only for the specific entry type.

So, I'll make a fix that removes the partial template include from single.html since that's just a bug (interestingly it didn't show up twice, but it doesn't need to be there), and you can remove it from page.html as well so that it only appears in posts. Hope that helps!

**Comment by halogenica** [comment]
Just checked in fix to remove the Disqus comments from the "single.html" partial.

**Comment by refactorsaurusrex** [comment]
> (interestingly it didn't show up twice, but it doesn't need to be there)

Yeah I noticed that too - which doubled my confusion! haha. 

> Just checked in fix to remove the Disqus comments from the "single.html" partial.

Sweet, thanks man!
